
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.app
{
public sealed partial class app_config : Luban.BeanBase
{
    public app_config(ByteBuf _buf) 
    {
        ServerHost = _buf.ReadString();
    }

    public static app_config Deserializeapp_config(ByteBuf _buf)
    {
        return new app.app_config(_buf);
    }

    /// <summary>
    /// 服务器host
    /// </summary>
    public readonly string ServerHost;
   
    public const int __ID__ = 1042564365;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "serverHost:" + ServerHost + ","
        + "}";
    }
}
}

