
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.app
{
public partial class tb_app_config
{

     private readonly app.app_config _data;

     public app.app_config Data => _data;

    public tb_app_config(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.app.app_config.Deserializeapp_config(_buf);
    }


    /// <summary>
    /// 服务器host
    /// </summary>
     public string ServerHost => _data.ServerHost;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

