
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class item_info : Luban.BeanBase
{
    public item_info(ByteBuf _buf) 
    {
        ItemId = (item_ID)_buf.ReadInt();
        MainType = (item_main_type)_buf.ReadInt();
        if(_buf.ReadBool()){ SubType = (item_sub_type)_buf.ReadInt(); } else { SubType = null; }
        ItemName = _buf.ReadString();
    }

    public static item_info Deserializeitem_info(ByteBuf _buf)
    {
        return new item.item_info(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly item_ID ItemId;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly item_main_type MainType;
    /// <summary>
    /// 子类型
    /// </summary>
    public readonly item_sub_type? SubType;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string ItemName;
   
    public const int __ID__ = -1956976321;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "mainType:" + MainType + ","
        + "subType:" + SubType + ","
        + "itemName:" + ItemName + ","
        + "}";
    }
}
}

