
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class tb_item_info
{
    private readonly System.Collections.Generic.Dictionary<item_ID, item.item_info> _dataMap;
    private readonly System.Collections.Generic.List<item.item_info> _dataList;
    
    public tb_item_info(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<item_ID, item.item_info>(n);
        _dataList = new System.Collections.Generic.List<item.item_info>(n);
        for(int i = n ; i > 0 ; --i)
        {
            item.item_info _v;
            _v = global::GameConfig.item.item_info.Deserializeitem_info(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<item_ID, item.item_info> DataMap => _dataMap;
    public System.Collections.Generic.List<item.item_info> DataList => _dataList;

    public item.item_info GetOrDefault(item_ID key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public item.item_info Get(item_ID key) => _dataMap[key];
    public item.item_info this[item_ID key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

