// <auto-generated>
// Generated by Proto MessageId generator.
// </auto-generated>

namespace chinese_chess_game
{
    public static partial class MessageId
    {
        public const int gameStateReq = 10101;
        public const int gameStateRes = 10102;
        public const int moveReq = 10103;
        public const int moveRes = 10104;
        public const int nextDoing = 10180;
    }
}

namespace errors
{
    public static partial class MessageId
    {
        public const int Error = 101;
    }
}

namespace login
{
    public static partial class MessageId
    {
        public const int LoginReq = 201;
        public const int LoginRes = 202;
        public const int HeartReq = 203;
        public const int HeartRes = 204;
    }
}

namespace game_hall
{
    public static partial class MessageId
    {
        public const int JoinReq = 5101;
        public const int JoinRes = 5102;
    }
}

namespace hallserver_player
{
    public static partial class MessageId
    {
        public const int ReqChangeNickName = 10101;
        public const int ResChangeNickName = 10102;
        public const int PlayerInfoNotice = 10180;
        public const int PlayerInfoSynNotice = 10181;
    }
}

namespace hallserver_item
{
    public static partial class MessageId
    {
        public const int ItemListNotice = 10280;
    }
}

namespace hallserver_match
{
    public static partial class MessageId
    {
        public const int MatchGameReq = 10301;
        public const int MatchGameRes = 10302;
        public const int CancelMatchGameReq = 10303;
        public const int CancelMatchGameRes = 10304;
        public const int AcceptMatchReq = 10305;
        public const int AcceptMatchRes = 10306;
        public const int MatchGameNotice = 10380;
        public const int JoinGameNotice = 10381;
    }
}

namespace hallserver_friend
{
    public static partial class MessageId
    {
        public const int AddFriendReq = 10401;
        public const int AddFriendRes = 10402;
        public const int AgreeAddFriendReq = 10403;
        public const int AgreeAddFriendRes = 10404;
        public const int RefuseAddFriendReq = 10405;
        public const int RefuseAddFriendRes = 10406;
        public const int DelFriendReq = 10407;
        public const int DelFriendRes = 10408;
        public const int FriendSugReq = 10409;
        public const int FriendSugRes = 10410;
        public const int FriendListNotice = 10481;
        public const int AddReqListNotice = 10482;
        public const int AddReqNotice = 10483;
        public const int AddFriendNotice = 10484;
        public const int DelFriendNotice = 10485;
    }
}

namespace hallserver_game_record
{
    public static partial class MessageId
    {
        public const int RecordListReq = 10501;
        public const int RecordListRes = 10502;
    }
}

namespace hallserver_email
{
    public static partial class MessageId
    {
        public const int ReadEmailReq = 10601;
        public const int ReadEmailRes = 10602;
        public const int ItemListEmailReq = 10603;
        public const int ItemListEmailRes = 10604;
        public const int DelEmailReq = 10605;
        public const int DelEmailRes = 10606;
        public const int AllEmailNotice = 10680;
        public const int OneEmailNotice = 10681;
        public const int DelEmailNotice = 10682;
    }
}

