
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.misc
{
public sealed partial class misc_param : Luban.BeanBase
{
    public misc_param(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); LoginRewards = new System.Collections.Generic.Dictionary<item_ID, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { item_ID _k0;  _k0 = (item_ID)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     LoginRewards.Add(_k0, _v0);}}
    }

    public static misc_param Deserializemisc_param(ByteBuf _buf)
    {
        return new misc.misc_param(_buf);
    }

    /// <summary>
    /// 每日登录奖励
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<item_ID, int> LoginRewards;
   
    public const int __ID__ = 1627794876;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "loginRewards:" + Luban.StringUtil.CollectionToString(LoginRewards) + ","
        + "}";
    }
}
}

