
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.misc
{
public partial class tb_misc_param
{

     private readonly misc.misc_param _data;

     public misc.misc_param Data => _data;

    public tb_misc_param(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.misc.misc_param.Deserializemisc_param(_buf);
    }


    /// <summary>
    /// 每日登录奖励
    /// </summary>
     public System.Collections.Generic.Dictionary<item_ID, int> LoginRewards => _data.LoginRewards;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

