// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 51-game_hall.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace game_hall
{

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string table_id
        {
            get => __pbn__table_id ?? "";
            set => __pbn__table_id = value;
        }
        public bool ShouldSerializetable_id() => __pbn__table_id != null;
        public void Resettable_id() => __pbn__table_id = null;
        private string __pbn__table_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string table_id
        {
            get => __pbn__table_id ?? "";
            set => __pbn__table_id = value;
        }
        public bool ShouldSerializetable_id() => __pbn__table_id != null;
        public void Resettable_id() => __pbn__table_id = null;
        private string __pbn__table_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        game_hall = 51,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        JoinReq = 1,
        JoinRes = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
