
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.match
{
public sealed partial class match_game : Luban.BeanBase
{
    public match_game(ByteBuf _buf) 
    {
        GameType = (game_type)_buf.ReadInt();
        PlayType = (play_type)_buf.ReadInt();
    }

    public static match_game Deserializematch_game(ByteBuf _buf)
    {
        return new match.match_game(_buf);
    }

    /// <summary>
    /// 游戏类型
    /// </summary>
    public readonly game_type GameType;
    /// <summary>
    /// 玩法类型
    /// </summary>
    public readonly play_type PlayType;
   
    public const int __ID__ = -53189131;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "gameType:" + GameType + ","
        + "playType:" + PlayType + ","
        + "}";
    }
}
}

