
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.match
{
public partial class tb_match_game
{
    private readonly System.Collections.Generic.List<match.match_game> _dataList;


    public tb_match_game(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<match.match_game>(n);
        for(int i = n ; i > 0 ; --i)
        {
            match.match_game _v;
            _v = global::GameConfig.match.match_game.Deserializematch_game(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<match.match_game> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

