
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chess
{
public sealed partial class chess_param : Luban.BeanBase
{
    public chess_param(ByteBuf _buf) 
    {
        InitScore = _buf.ReadInt();
        LowLevelCond = _buf.ReadInt();
        WinAddScore = _buf.ReadInt();
        LoseReduceScore = _buf.ReadInt();
        LowWinAddScore = _buf.ReadInt();
        LowLoseReduceScore = _buf.ReadInt();
    }

    public static chess_param Deserializechess_param(ByteBuf _buf)
    {
        return new chess.chess_param(_buf);
    }

    /// <summary>
    /// 初始分数
    /// </summary>
    public readonly int InitScore;
    /// <summary>
    /// 低等级条件
    /// </summary>
    public readonly int LowLevelCond;
    /// <summary>
    /// 赢加分
    /// </summary>
    public readonly int WinAddScore;
    /// <summary>
    /// 输减分
    /// </summary>
    public readonly int LoseReduceScore;
    /// <summary>
    /// 低等级赢加分
    /// </summary>
    public readonly int LowWinAddScore;
    /// <summary>
    /// 低等级输减分
    /// </summary>
    public readonly int LowLoseReduceScore;
   
    public const int __ID__ = -1388560224;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "initScore:" + InitScore + ","
        + "lowLevelCond:" + LowLevelCond + ","
        + "winAddScore:" + WinAddScore + ","
        + "loseReduceScore:" + LoseReduceScore + ","
        + "lowWinAddScore:" + LowWinAddScore + ","
        + "lowLoseReduceScore:" + LowLoseReduceScore + ","
        + "}";
    }
}
}

