
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chess
{
public sealed partial class chess_type : Luban.BeanBase
{
    public chess_type(ByteBuf _buf) 
    {
        PlayType = (play_type)_buf.ReadInt();
        TotalTime = _buf.ReadInt();
        DoingTime = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); WinRewards = new System.Collections.Generic.Dictionary<item_ID, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { item_ID _k0;  _k0 = (item_ID)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     WinRewards.Add(_k0, _v0);}}
        {int n0 = _buf.ReadSize(); FailRewards = new System.Collections.Generic.Dictionary<item_ID, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { item_ID _k0;  _k0 = (item_ID)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     FailRewards.Add(_k0, _v0);}}
    }

    public static chess_type Deserializechess_type(ByteBuf _buf)
    {
        return new chess.chess_type(_buf);
    }

    /// <summary>
    /// 玩法类型
    /// </summary>
    public readonly play_type PlayType;
    /// <summary>
    /// 总局时(秒)
    /// </summary>
    public readonly int TotalTime;
    /// <summary>
    /// 操作时长(秒)
    /// </summary>
    public readonly int DoingTime;
    /// <summary>
    /// 获胜奖励
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<item_ID, int> WinRewards;
    /// <summary>
    /// 失败奖励
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<item_ID, int> FailRewards;
   
    public const int __ID__ = 1895012551;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "playType:" + PlayType + ","
        + "totalTime:" + TotalTime + ","
        + "doingTime:" + DoingTime + ","
        + "winRewards:" + Luban.StringUtil.CollectionToString(WinRewards) + ","
        + "failRewards:" + Luban.StringUtil.CollectionToString(FailRewards) + ","
        + "}";
    }
}
}

