
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chess
{
public sealed partial class chess_rank : Luban.BeanBase
{
    public chess_rank(ByteBuf _buf) 
    {
        RankId = _buf.ReadInt();
        Level = _buf.ReadInt();
        RankName = _buf.ReadString();
        NeedScore = _buf.ReadInt();
    }

    public static chess_rank Deserializechess_rank(ByteBuf _buf)
    {
        return new chess.chess_rank(_buf);
    }

    /// <summary>
    /// 段位ID
    /// </summary>
    public readonly int RankId;
    /// <summary>
    /// 段位等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 段位名称
    /// </summary>
    public readonly string RankName;
    /// <summary>
    /// 目标分数
    /// </summary>
    public readonly int NeedScore;
   
    public const int __ID__ = 1894929849;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rankId:" + RankId + ","
        + "level:" + Level + ","
        + "rankName:" + RankName + ","
        + "needScore:" + NeedScore + ","
        + "}";
    }
}
}

