
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chess
{
public partial class tb_chess_param
{

     private readonly chess.chess_param _data;

     public chess.chess_param Data => _data;

    public tb_chess_param(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.chess.chess_param.Deserializechess_param(_buf);
    }


    /// <summary>
    /// 初始分数
    /// </summary>
     public int InitScore => _data.InitScore;
    /// <summary>
    /// 低等级条件
    /// </summary>
     public int LowLevelCond => _data.LowLevelCond;
    /// <summary>
    /// 赢加分
    /// </summary>
     public int WinAddScore => _data.WinAddScore;
    /// <summary>
    /// 输减分
    /// </summary>
     public int LoseReduceScore => _data.LoseReduceScore;
    /// <summary>
    /// 低等级赢加分
    /// </summary>
     public int LowWinAddScore => _data.LowWinAddScore;
    /// <summary>
    /// 低等级输减分
    /// </summary>
     public int LowLoseReduceScore => _data.LowLoseReduceScore;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

