
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chess
{
public partial class tb_chess_type
{
    private readonly System.Collections.Generic.Dictionary<play_type, chess.chess_type> _dataMap;
    private readonly System.Collections.Generic.List<chess.chess_type> _dataList;
    
    public tb_chess_type(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<play_type, chess.chess_type>(n);
        _dataList = new System.Collections.Generic.List<chess.chess_type>(n);
        for(int i = n ; i > 0 ; --i)
        {
            chess.chess_type _v;
            _v = global::GameConfig.chess.chess_type.Deserializechess_type(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.PlayType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<play_type, chess.chess_type> DataMap => _dataMap;
    public System.Collections.Generic.List<chess.chess_type> DataList => _dataList;

    public chess.chess_type GetOrDefault(play_type key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public chess.chess_type Get(play_type key) => _dataMap[key];
    public chess.chess_type this[play_type key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

