
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.chess
{
public partial class tb_chess_rank
{
    private readonly System.Collections.Generic.Dictionary<int, chess.chess_rank> _dataMap;
    private readonly System.Collections.Generic.List<chess.chess_rank> _dataList;
    
    public tb_chess_rank(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, chess.chess_rank>(n);
        _dataList = new System.Collections.Generic.List<chess.chess_rank>(n);
        for(int i = n ; i > 0 ; --i)
        {
            chess.chess_rank _v;
            _v = global::GameConfig.chess.chess_rank.Deserializechess_rank(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RankId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, chess.chess_rank> DataMap => _dataMap;
    public System.Collections.Generic.List<chess.chess_rank> DataList => _dataList;

    public chess.chess_rank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public chess.chess_rank Get(int key) => _dataMap[key];
    public chess.chess_rank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

