
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.player
{
public sealed partial class player_level : Luban.BeanBase
{
    public player_level(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        Exp = _buf.ReadInt();
    }

    public static player_level Deserializeplayer_level(ByteBuf _buf)
    {
        return new player.player_level(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 经验
    /// </summary>
    public readonly int Exp;
   
    public const int __ID__ = -12569965;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "exp:" + Exp + ","
        + "}";
    }
}
}

