
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.player
{
public partial class tb_player_level
{
    private readonly System.Collections.Generic.Dictionary<int, player.player_level> _dataMap;
    private readonly System.Collections.Generic.List<player.player_level> _dataList;
    
    public tb_player_level(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, player.player_level>(n);
        _dataList = new System.Collections.Generic.List<player.player_level>(n);
        for(int i = n ; i > 0 ; --i)
        {
            player.player_level _v;
            _v = global::GameConfig.player.player_level.Deserializeplayer_level(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, player.player_level> DataMap => _dataMap;
    public System.Collections.Generic.List<player.player_level> DataList => _dataList;

    public player.player_level GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public player.player_level Get(int key) => _dataMap[key];
    public player.player_level this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

