// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 101-chinese_chess_game.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace chinese_chess_game
{

    [global::ProtoBuf.ProtoContract()]
    public partial class gameStateReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long player_id
        {
            get => __pbn__player_id.GetValueOrDefault();
            set => __pbn__player_id = value;
        }
        public bool ShouldSerializeplayer_id() => __pbn__player_id != null;
        public void Resetplayer_id() => __pbn__player_id = null;
        private long? __pbn__player_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class playerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int seat_id
        {
            get => __pbn__seat_id.GetValueOrDefault();
            set => __pbn__seat_id = value;
        }
        public bool ShouldSerializeseat_id() => __pbn__seat_id != null;
        public void Resetseat_id() => __pbn__seat_id = null;
        private int? __pbn__seat_id;

        [global::ProtoBuf.ProtoMember(2)]
        public long player_id
        {
            get => __pbn__player_id.GetValueOrDefault();
            set => __pbn__player_id = value;
        }
        public bool ShouldSerializeplayer_id() => __pbn__player_id != null;
        public void Resetplayer_id() => __pbn__player_id = null;
        private long? __pbn__player_id;

        [global::ProtoBuf.ProtoMember(3)]
        public int team_type
        {
            get => __pbn__team_type.GetValueOrDefault();
            set => __pbn__team_type = value;
        }
        public bool ShouldSerializeteam_type() => __pbn__team_type != null;
        public void Resetteam_type() => __pbn__team_type = null;
        private int? __pbn__team_type;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname
        {
            get => __pbn__nickname ?? "";
            set => __pbn__nickname = value;
        }
        public bool ShouldSerializenickname() => __pbn__nickname != null;
        public void Resetnickname() => __pbn__nickname = null;
        private string __pbn__nickname;

        [global::ProtoBuf.ProtoMember(5)]
        public int score
        {
            get => __pbn__score.GetValueOrDefault();
            set => __pbn__score = value;
        }
        public bool ShouldSerializescore() => __pbn__score != null;
        public void Resetscore() => __pbn__score = null;
        private int? __pbn__score;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class oneChess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chess_id
        {
            get => __pbn__chess_id.GetValueOrDefault();
            set => __pbn__chess_id = value;
        }
        public bool ShouldSerializechess_id() => __pbn__chess_id != null;
        public void Resetchess_id() => __pbn__chess_id = null;
        private int? __pbn__chess_id;

        [global::ProtoBuf.ProtoMember(2)]
        public int chess_type
        {
            get => __pbn__chess_type.GetValueOrDefault();
            set => __pbn__chess_type = value;
        }
        public bool ShouldSerializechess_type() => __pbn__chess_type != null;
        public void Resetchess_type() => __pbn__chess_type = null;
        private int? __pbn__chess_type;

        [global::ProtoBuf.ProtoMember(3)]
        public int row
        {
            get => __pbn__row.GetValueOrDefault();
            set => __pbn__row = value;
        }
        public bool ShouldSerializerow() => __pbn__row != null;
        public void Resetrow() => __pbn__row = null;
        private int? __pbn__row;

        [global::ProtoBuf.ProtoMember(4)]
        public int col
        {
            get => __pbn__col.GetValueOrDefault();
            set => __pbn__col = value;
        }
        public bool ShouldSerializecol() => __pbn__col != null;
        public void Resetcol() => __pbn__col = null;
        private int? __pbn__col;

        [global::ProtoBuf.ProtoMember(5)]
        public int team_type
        {
            get => __pbn__team_type.GetValueOrDefault();
            set => __pbn__team_type = value;
        }
        public bool ShouldSerializeteam_type() => __pbn__team_type != null;
        public void Resetteam_type() => __pbn__team_type = null;
        private int? __pbn__team_type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class chessCanMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chess_id
        {
            get => __pbn__chess_id.GetValueOrDefault();
            set => __pbn__chess_id = value;
        }
        public bool ShouldSerializechess_id() => __pbn__chess_id != null;
        public void Resetchess_id() => __pbn__chess_id = null;
        private int? __pbn__chess_id;

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public int[] row_list { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public int[] col_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class nextDoing : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int seat_id
        {
            get => __pbn__seat_id.GetValueOrDefault();
            set => __pbn__seat_id = value;
        }
        public bool ShouldSerializeseat_id() => __pbn__seat_id != null;
        public void Resetseat_id() => __pbn__seat_id = null;
        private int? __pbn__seat_id;

        [global::ProtoBuf.ProtoMember(2)]
        public long player_id
        {
            get => __pbn__player_id.GetValueOrDefault();
            set => __pbn__player_id = value;
        }
        public bool ShouldSerializeplayer_id() => __pbn__player_id != null;
        public void Resetplayer_id() => __pbn__player_id = null;
        private long? __pbn__player_id;

        [global::ProtoBuf.ProtoMember(3)]
        public int team_type
        {
            get => __pbn__team_type.GetValueOrDefault();
            set => __pbn__team_type = value;
        }
        public bool ShouldSerializeteam_type() => __pbn__team_type != null;
        public void Resetteam_type() => __pbn__team_type = null;
        private int? __pbn__team_type;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<chessCanMove> can_move_list { get; } = new global::System.Collections.Generic.List<chessCanMove>();

        [global::ProtoBuf.ProtoMember(5)]
        public int remain_total_time
        {
            get => __pbn__remain_total_time.GetValueOrDefault();
            set => __pbn__remain_total_time = value;
        }
        public bool ShouldSerializeremain_total_time() => __pbn__remain_total_time != null;
        public void Resetremain_total_time() => __pbn__remain_total_time = null;
        private int? __pbn__remain_total_time;

        [global::ProtoBuf.ProtoMember(6)]
        public int remain_once_time
        {
            get => __pbn__remain_once_time.GetValueOrDefault();
            set => __pbn__remain_once_time = value;
        }
        public bool ShouldSerializeremain_once_time() => __pbn__remain_once_time != null;
        public void Resetremain_once_time() => __pbn__remain_once_time = null;
        private int? __pbn__remain_once_time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class gameStateRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int state
        {
            get => __pbn__state.GetValueOrDefault();
            set => __pbn__state = value;
        }
        public bool ShouldSerializestate() => __pbn__state != null;
        public void Resetstate() => __pbn__state = null;
        private int? __pbn__state;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<playerInfo> player_list { get; } = new global::System.Collections.Generic.List<playerInfo>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<oneChess> chess_list { get; } = new global::System.Collections.Generic.List<oneChess>();

        [global::ProtoBuf.ProtoMember(4)]
        public nextDoing next_doing { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long win_player_id
        {
            get => __pbn__win_player_id.GetValueOrDefault();
            set => __pbn__win_player_id = value;
        }
        public bool ShouldSerializewin_player_id() => __pbn__win_player_id != null;
        public void Resetwin_player_id() => __pbn__win_player_id = null;
        private long? __pbn__win_player_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class moveReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chess_id
        {
            get => __pbn__chess_id.GetValueOrDefault();
            set => __pbn__chess_id = value;
        }
        public bool ShouldSerializechess_id() => __pbn__chess_id != null;
        public void Resetchess_id() => __pbn__chess_id = null;
        private int? __pbn__chess_id;

        [global::ProtoBuf.ProtoMember(2)]
        public int move_row
        {
            get => __pbn__move_row.GetValueOrDefault();
            set => __pbn__move_row = value;
        }
        public bool ShouldSerializemove_row() => __pbn__move_row != null;
        public void Resetmove_row() => __pbn__move_row = null;
        private int? __pbn__move_row;

        [global::ProtoBuf.ProtoMember(3)]
        public int move_col
        {
            get => __pbn__move_col.GetValueOrDefault();
            set => __pbn__move_col = value;
        }
        public bool ShouldSerializemove_col() => __pbn__move_col != null;
        public void Resetmove_col() => __pbn__move_col = null;
        private int? __pbn__move_col;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class moveRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int chess_id
        {
            get => __pbn__chess_id.GetValueOrDefault();
            set => __pbn__chess_id = value;
        }
        public bool ShouldSerializechess_id() => __pbn__chess_id != null;
        public void Resetchess_id() => __pbn__chess_id = null;
        private int? __pbn__chess_id;

        [global::ProtoBuf.ProtoMember(2)]
        public int move_row
        {
            get => __pbn__move_row.GetValueOrDefault();
            set => __pbn__move_row = value;
        }
        public bool ShouldSerializemove_row() => __pbn__move_row != null;
        public void Resetmove_row() => __pbn__move_row = null;
        private int? __pbn__move_row;

        [global::ProtoBuf.ProtoMember(3)]
        public int move_col
        {
            get => __pbn__move_col.GetValueOrDefault();
            set => __pbn__move_col = value;
        }
        public bool ShouldSerializemove_col() => __pbn__move_col != null;
        public void Resetmove_col() => __pbn__move_col = null;
        private int? __pbn__move_col;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        chinese_chess_game = 101,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        gameStateReq = 1,
        gameStateRes = 2,
        moveReq = 3,
        moveRes = 4,
        nextDoing = 80,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
