
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 邮件类型
    /// </summary>
    public enum email_type
    {
        /// <summary>
        /// 全服邮件
        /// </summary>
        GLOBAL = 1,
        /// <summary>
        /// 系统邮件
        /// </summary>
        SYSTEM = 2,
        /// <summary>
        /// 好友邮件
        /// </summary>
        FRIEND = 3,
    }

} 

