
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 好友邮件ID
    /// </summary>
    public enum friend_email_id
    {
        /// <summary>
        /// 好友金币赠送
        /// </summary>
        GOLD_REWARD = 0,
    }

} 

