
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 游戏类型
    /// </summary>
    public enum game_type
    {
        /// <summary>
        /// 中国象棋游戏
        /// </summary>
        CHINESE_CHESS = 1,
        /// <summary>
        /// 数字炸弹游戏
        /// </summary>
        DIGITALBOMB = 2,
    }

} 

