
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum item_main_type
    {
        /// <summary>
        /// 没有特殊类型的道具
        /// </summary>
        PROP = 1,
    }

} 

