
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 道具ID
    /// </summary>
    public enum item_ID
    {
        /// <summary>
        /// 普通货币
        /// </summary>
        PROP_SILVER = 10000001,
        /// <summary>
        /// 高级货币
        /// </summary>
        PROP_GOLD = 10000002,
        /// <summary>
        /// 玩家经验值
        /// </summary>
        PROP_EXP = 10000003,
    }

} 

