
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 玩法类型
    /// </summary>
    public enum play_type
    {
        /// <summary>
        /// 排位赛玩法
        /// </summary>
        CC_RANKING = 10001,
        /// <summary>
        /// 5分钟场
        /// </summary>
        CC_FIVE_MINUTE = 10002,
        /// <summary>
        /// 10分钟场
        /// </summary>
        CC_TEN_MINUTE = 10003,
        /// <summary>
        /// 范围100玩法
        /// </summary>
        DB_RANGE_100 = 20001,
        /// <summary>
        /// 范围10000玩法
        /// </summary>
        DB_RANGE_10000 = 20002,
    }

} 

