
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    /// <summary>
    /// 系统邮件ID
    /// </summary>
    public enum sys_email_id
    {
        /// <summary>
        /// 每日登录奖励
        /// </summary>
        LOGIN_REWARD = 0,
    }

} 

