// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 101-hallserver_player.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hallserver_player
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInfoNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname
        {
            get => __pbn__nickname ?? "";
            set => __pbn__nickname = value;
        }
        public bool ShouldSerializenickname() => __pbn__nickname != null;
        public void Resetnickname() => __pbn__nickname = null;
        private string __pbn__nickname;

        [global::ProtoBuf.ProtoMember(2)]
        public int rank_score
        {
            get => __pbn__rank_score.GetValueOrDefault();
            set => __pbn__rank_score = value;
        }
        public bool ShouldSerializerank_score() => __pbn__rank_score != null;
        public void Resetrank_score() => __pbn__rank_score = null;
        private int? __pbn__rank_score;

        [global::ProtoBuf.ProtoMember(3)]
        public int level
        {
            get => __pbn__level.GetValueOrDefault();
            set => __pbn__level = value;
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(4)]
        public int head_frame_id
        {
            get => __pbn__head_frame_id.GetValueOrDefault();
            set => __pbn__head_frame_id = value;
        }
        public bool ShouldSerializehead_frame_id() => __pbn__head_frame_id != null;
        public void Resethead_frame_id() => __pbn__head_frame_id = null;
        private int? __pbn__head_frame_id;

        [global::ProtoBuf.ProtoMember(5)]
        public int head_id
        {
            get => __pbn__head_id.GetValueOrDefault();
            set => __pbn__head_id = value;
        }
        public bool ShouldSerializehead_id() => __pbn__head_id != null;
        public void Resethead_id() => __pbn__head_id = null;
        private int? __pbn__head_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class oneSynInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string field_name
        {
            get => __pbn__field_name ?? "";
            set => __pbn__field_name = value;
        }
        public bool ShouldSerializefield_name() => __pbn__field_name != null;
        public void Resetfield_name() => __pbn__field_name = null;
        private string __pbn__field_name;

        [global::ProtoBuf.ProtoMember(2)]
        public int is_str
        {
            get => __pbn__is_str.GetValueOrDefault();
            set => __pbn__is_str = value;
        }
        public bool ShouldSerializeis_str() => __pbn__is_str != null;
        public void Resetis_str() => __pbn__is_str = null;
        private int? __pbn__is_str;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string value_str
        {
            get => __pbn__value_str ?? "";
            set => __pbn__value_str = value;
        }
        public bool ShouldSerializevalue_str() => __pbn__value_str != null;
        public void Resetvalue_str() => __pbn__value_str = null;
        private string __pbn__value_str;

        [global::ProtoBuf.ProtoMember(4)]
        public long value
        {
            get => __pbn__value.GetValueOrDefault();
            set => __pbn__value = value;
        }
        public bool ShouldSerializevalue() => __pbn__value != null;
        public void Resetvalue() => __pbn__value = null;
        private long? __pbn__value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInfoSynNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long player_id
        {
            get => __pbn__player_id.GetValueOrDefault();
            set => __pbn__player_id = value;
        }
        public bool ShouldSerializeplayer_id() => __pbn__player_id != null;
        public void Resetplayer_id() => __pbn__player_id = null;
        private long? __pbn__player_id;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<oneSynInfo> synList { get; } = new global::System.Collections.Generic.List<oneSynInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqChangeNickName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname
        {
            get => __pbn__nickname ?? "";
            set => __pbn__nickname = value;
        }
        public bool ShouldSerializenickname() => __pbn__nickname != null;
        public void Resetnickname() => __pbn__nickname = null;
        private string __pbn__nickname;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResChangeNickName : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname
        {
            get => __pbn__nickname ?? "";
            set => __pbn__nickname = value;
        }
        public bool ShouldSerializenickname() => __pbn__nickname != null;
        public void Resetnickname() => __pbn__nickname = null;
        private string __pbn__nickname;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        hallserver_player = 101,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        ReqChangeNickName = 1,
        ResChangeNickName = 2,
        PlayerInfoNotice = 80,
        PlayerInfoSynNotice = 81,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
