// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 103-hallserver_match.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hallserver_match
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchGameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(2)]
        public int play_type
        {
            get => __pbn__play_type.GetValueOrDefault();
            set => __pbn__play_type = value;
        }
        public bool ShouldSerializeplay_type() => __pbn__play_type != null;
        public void Resetplay_type() => __pbn__play_type = null;
        private int? __pbn__play_type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchGameRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelMatchGameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CancelMatchGameRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchGameNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string session_id
        {
            get => __pbn__session_id ?? "";
            set => __pbn__session_id = value;
        }
        public bool ShouldSerializesession_id() => __pbn__session_id != null;
        public void Resetsession_id() => __pbn__session_id = null;
        private string __pbn__session_id;

        [global::ProtoBuf.ProtoMember(3)]
        public int remain_time
        {
            get => __pbn__remain_time.GetValueOrDefault();
            set => __pbn__remain_time = value;
        }
        public bool ShouldSerializeremain_time() => __pbn__remain_time != null;
        public void Resetremain_time() => __pbn__remain_time = null;
        private int? __pbn__remain_time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AcceptMatchReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string session_id
        {
            get => __pbn__session_id ?? "";
            set => __pbn__session_id = value;
        }
        public bool ShouldSerializesession_id() => __pbn__session_id != null;
        public void Resetsession_id() => __pbn__session_id = null;
        private string __pbn__session_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AcceptMatchRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string session_id
        {
            get => __pbn__session_id ?? "";
            set => __pbn__session_id = value;
        }
        public bool ShouldSerializesession_id() => __pbn__session_id != null;
        public void Resetsession_id() => __pbn__session_id = null;
        private string __pbn__session_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinGameNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gamehost
        {
            get => __pbn__gamehost ?? "";
            set => __pbn__gamehost = value;
        }
        public bool ShouldSerializegamehost() => __pbn__gamehost != null;
        public void Resetgamehost() => __pbn__gamehost = null;
        private string __pbn__gamehost;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gametoken
        {
            get => __pbn__gametoken ?? "";
            set => __pbn__gametoken = value;
        }
        public bool ShouldSerializegametoken() => __pbn__gametoken != null;
        public void Resetgametoken() => __pbn__gametoken = null;
        private string __pbn__gametoken;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string table_id
        {
            get => __pbn__table_id ?? "";
            set => __pbn__table_id = value;
        }
        public bool ShouldSerializetable_id() => __pbn__table_id != null;
        public void Resettable_id() => __pbn__table_id = null;
        private string __pbn__table_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        hallserver_match = 103,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        MatchGameReq = 1,
        MatchGameRes = 2,
        CancelMatchGameReq = 3,
        CancelMatchGameRes = 4,
        AcceptMatchReq = 5,
        AcceptMatchRes = 6,
        MatchGameNotice = 80,
        JoinGameNotice = 81,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
