// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 105-hallserver_game_record.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hallserver_game_record
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OneRecord : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long create_time
        {
            get => __pbn__create_time.GetValueOrDefault();
            set => __pbn__create_time = value;
        }
        public bool ShouldSerializecreate_time() => __pbn__create_time != null;
        public void Resetcreate_time() => __pbn__create_time = null;
        private long? __pbn__create_time;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string table_id
        {
            get => __pbn__table_id ?? "";
            set => __pbn__table_id = value;
        }
        public bool ShouldSerializetable_id() => __pbn__table_id != null;
        public void Resettable_id() => __pbn__table_id = null;
        private string __pbn__table_id;

        [global::ProtoBuf.ProtoMember(3)]
        public int game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private int? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(4)]
        public int score
        {
            get => __pbn__score.GetValueOrDefault();
            set => __pbn__score = value;
        }
        public bool ShouldSerializescore() => __pbn__score != null;
        public void Resetscore() => __pbn__score = null;
        private int? __pbn__score;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecordListReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint pageage_num
        {
            get => __pbn__pageage_num.GetValueOrDefault();
            set => __pbn__pageage_num = value;
        }
        public bool ShouldSerializepageage_num() => __pbn__pageage_num != null;
        public void Resetpageage_num() => __pbn__pageage_num = null;
        private uint? __pbn__pageage_num;

        [global::ProtoBuf.ProtoMember(2)]
        public uint pageage_count
        {
            get => __pbn__pageage_count.GetValueOrDefault();
            set => __pbn__pageage_count = value;
        }
        public bool ShouldSerializepageage_count() => __pbn__pageage_count != null;
        public void Resetpageage_count() => __pbn__pageage_count = null;
        private uint? __pbn__pageage_count;

        [global::ProtoBuf.ProtoMember(3)]
        public uint cursor
        {
            get => __pbn__cursor.GetValueOrDefault();
            set => __pbn__cursor = value;
        }
        public bool ShouldSerializecursor() => __pbn__cursor != null;
        public void Resetcursor() => __pbn__cursor = null;
        private uint? __pbn__cursor;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecordListRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint pageage_num
        {
            get => __pbn__pageage_num.GetValueOrDefault();
            set => __pbn__pageage_num = value;
        }
        public bool ShouldSerializepageage_num() => __pbn__pageage_num != null;
        public void Resetpageage_num() => __pbn__pageage_num = null;
        private uint? __pbn__pageage_num;

        [global::ProtoBuf.ProtoMember(2)]
        public uint pageage_count
        {
            get => __pbn__pageage_count.GetValueOrDefault();
            set => __pbn__pageage_count = value;
        }
        public bool ShouldSerializepageage_count() => __pbn__pageage_count != null;
        public void Resetpageage_count() => __pbn__pageage_count = null;
        private uint? __pbn__pageage_count;

        [global::ProtoBuf.ProtoMember(3)]
        public uint total_count
        {
            get => __pbn__total_count.GetValueOrDefault();
            set => __pbn__total_count = value;
        }
        public bool ShouldSerializetotal_count() => __pbn__total_count != null;
        public void Resettotal_count() => __pbn__total_count = null;
        private uint? __pbn__total_count;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<OneRecord> record_list { get; } = new global::System.Collections.Generic.List<OneRecord>();

        [global::ProtoBuf.ProtoMember(5)]
        public uint next_cursor
        {
            get => __pbn__next_cursor.GetValueOrDefault();
            set => __pbn__next_cursor = value;
        }
        public bool ShouldSerializenext_cursor() => __pbn__next_cursor != null;
        public void Resetnext_cursor() => __pbn__next_cursor = null;
        private uint? __pbn__next_cursor;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        hallserver_game_record = 105,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        RecordListReq = 1,
        RecordListRes = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
