// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 106-hallserver_email.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hallserver_email
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadEmailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReadEmailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemListEmailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemListEmailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DelEmailReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DelEmailRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class oneEmail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long guid
        {
            get => __pbn__guid.GetValueOrDefault();
            set => __pbn__guid = value;
        }
        public bool ShouldSerializeguid() => __pbn__guid != null;
        public void Resetguid() => __pbn__guid = null;
        private long? __pbn__guid;

        [global::ProtoBuf.ProtoMember(2)]
        public int email_type
        {
            get => __pbn__email_type.GetValueOrDefault();
            set => __pbn__email_type = value;
        }
        public bool ShouldSerializeemail_type() => __pbn__email_type != null;
        public void Resetemail_type() => __pbn__email_type = null;
        private int? __pbn__email_type;

        [global::ProtoBuf.ProtoMember(3)]
        public long from_id
        {
            get => __pbn__from_id.GetValueOrDefault();
            set => __pbn__from_id = value;
        }
        public bool ShouldSerializefrom_id() => __pbn__from_id != null;
        public void Resetfrom_id() => __pbn__from_id = null;
        private long? __pbn__from_id;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string title
        {
            get => __pbn__title ?? "";
            set => __pbn__title = value;
        }
        public bool ShouldSerializetitle() => __pbn__title != null;
        public void Resettitle() => __pbn__title = null;
        private string __pbn__title;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content
        {
            get => __pbn__content ?? "";
            set => __pbn__content = value;
        }
        public bool ShouldSerializecontent() => __pbn__content != null;
        public void Resetcontent() => __pbn__content = null;
        private string __pbn__content;

        [global::ProtoBuf.ProtoMember(6)]
        public long create_time
        {
            get => __pbn__create_time.GetValueOrDefault();
            set => __pbn__create_time = value;
        }
        public bool ShouldSerializecreate_time() => __pbn__create_time != null;
        public void Resetcreate_time() => __pbn__create_time = null;
        private long? __pbn__create_time;

        [global::ProtoBuf.ProtoMember(7)]
        public long vaild_time
        {
            get => __pbn__vaild_time.GetValueOrDefault();
            set => __pbn__vaild_time = value;
        }
        public bool ShouldSerializevaild_time() => __pbn__vaild_time != null;
        public void Resetvaild_time() => __pbn__vaild_time = null;
        private long? __pbn__vaild_time;

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<global::common.Item> item_list { get; } = new global::System.Collections.Generic.List<global::common.Item>();

        [global::ProtoBuf.ProtoMember(9)]
        public int read_flag
        {
            get => __pbn__read_flag.GetValueOrDefault();
            set => __pbn__read_flag = value;
        }
        public bool ShouldSerializeread_flag() => __pbn__read_flag != null;
        public void Resetread_flag() => __pbn__read_flag = null;
        private int? __pbn__read_flag;

        [global::ProtoBuf.ProtoMember(10)]
        public int item_flag
        {
            get => __pbn__item_flag.GetValueOrDefault();
            set => __pbn__item_flag = value;
        }
        public bool ShouldSerializeitem_flag() => __pbn__item_flag != null;
        public void Resetitem_flag() => __pbn__item_flag = null;
        private int? __pbn__item_flag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AllEmailNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<oneEmail> email_list { get; } = new global::System.Collections.Generic.List<oneEmail>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OneEmailNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public oneEmail email { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DelEmailNotice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public long[] guid_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        hallserver_email = 106,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        ReadEmailReq = 1,
        ReadEmailRes = 2,
        ItemListEmailReq = 3,
        ItemListEmailRes = 4,
        DelEmailReq = 5,
        DelEmailRes = 6,
        AllEmailNotice = 80,
        OneEmailNotice = 81,
        DelEmailNotice = 82,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
