
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.email
{
public sealed partial class email_friend : Luban.BeanBase
{
    public email_friend(ByteBuf _buf) 
    {
        Id = (friend_email_id)_buf.ReadInt();
        Title = _buf.ReadString();
        Content = _buf.ReadString();
        VaildTime = _buf.ReadInt();
    }

    public static email_friend Deserializeemail_friend(ByteBuf _buf)
    {
        return new email.email_friend(_buf);
    }

    /// <summary>
    /// 好友邮件ID
    /// </summary>
    public readonly friend_email_id Id;
    /// <summary>
    /// 邮件标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 邮件内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 有效时间(秒)(0表示永久)
    /// </summary>
    public readonly int VaildTime;
   
    public const int __ID__ = 1435652531;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "content:" + Content + ","
        + "vaildTime:" + VaildTime + ","
        + "}";
    }
}
}

