
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.email
{
public partial class tb_email_sys
{
    private readonly System.Collections.Generic.Dictionary<sys_email_id, email.email_sys> _dataMap;
    private readonly System.Collections.Generic.List<email.email_sys> _dataList;
    
    public tb_email_sys(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<sys_email_id, email.email_sys>(n);
        _dataList = new System.Collections.Generic.List<email.email_sys>(n);
        for(int i = n ; i > 0 ; --i)
        {
            email.email_sys _v;
            _v = global::GameConfig.email.email_sys.Deserializeemail_sys(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<sys_email_id, email.email_sys> DataMap => _dataMap;
    public System.Collections.Generic.List<email.email_sys> DataList => _dataList;

    public email.email_sys GetOrDefault(sys_email_id key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public email.email_sys Get(sys_email_id key) => _dataMap[key];
    public email.email_sys this[sys_email_id key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

