
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.email
{
public partial class tb_email_friend
{
    private readonly System.Collections.Generic.List<email.email_friend> _dataList;


    public tb_email_friend(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<email.email_friend>(n);
        for(int i = n ; i > 0 ; --i)
        {
            email.email_friend _v;
            _v = global::GameConfig.email.email_friend.Deserializeemail_friend(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<email.email_friend> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

