// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 1-errors.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace errors
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Error : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get => __pbn__code.GetValueOrDefault();
            set => __pbn__code = value;
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msg
        {
            get => __pbn__msg ?? "";
            set => __pbn__msg = value;
        }
        public bool ShouldSerializemsg() => __pbn__msg != null;
        public void Resetmsg() => __pbn__msg = null;
        private string __pbn__msg;

        [global::ProtoBuf.ProtoMember(3)]
        public int pack_id
        {
            get => __pbn__pack_id.GetValueOrDefault();
            set => __pbn__pack_id = value;
        }
        public bool ShouldSerializepack_id() => __pbn__pack_id != null;
        public void Resetpack_id() => __pbn__pack_id = null;
        private int? __pbn__pack_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        errors = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        Error = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
