// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: 2-login.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace login
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token
        {
            get => __pbn__token ?? "";
            set => __pbn__token = value;
        }
        public bool ShouldSerializetoken() => __pbn__token != null;
        public void Resettoken() => __pbn__token = null;
        private string __pbn__token;

        [global::ProtoBuf.ProtoMember(2)]
        public long player_id
        {
            get => __pbn__player_id.GetValueOrDefault();
            set => __pbn__player_id = value;
        }
        public bool ShouldSerializeplayer_id() => __pbn__player_id != null;
        public void Resetplayer_id() => __pbn__player_id = null;
        private long? __pbn__player_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int isreconnect
        {
            get => __pbn__isreconnect.GetValueOrDefault();
            set => __pbn__isreconnect = value;
        }
        public bool ShouldSerializeisreconnect() => __pbn__isreconnect != null;
        public void Resetisreconnect() => __pbn__isreconnect = null;
        private int? __pbn__isreconnect;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long time
        {
            get => __pbn__time.GetValueOrDefault();
            set => __pbn__time = value;
        }
        public bool ShouldSerializetime() => __pbn__time != null;
        public void Resettime() => __pbn__time = null;
        private long? __pbn__time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartRes : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public long time
        {
            get => __pbn__time.GetValueOrDefault();
            set => __pbn__time = value;
        }
        public bool ShouldSerializetime() => __pbn__time != null;
        public void Resettime() => __pbn__time = null;
        private long? __pbn__time;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum main
    {
        login = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum sub
    {
        LoginReq = 1,
        LoginRes = 2,
        HeartReq = 3,
        HeartRes = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
